import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const server=await readFile(new URL('../../server/index.js',import.meta.url),'utf8');
const migration=await readFile(new URL('../../supabase/migrations/0023_v25_consolidation.sql',import.meta.url),'utf8');
const bridge=await readFile(new URL('../../print-bridge/bridge.mjs',import.meta.url),'utf8');
assert.match(server,/version: '25\.0\.0'/); assert.match(server,/rateLimit/); assert.match(server,/backups/); assert.match(server,/drivers/); assert.match(server,/payment/); assert.match(server,/listRealtimeEvents/);
assert.match(migration,/restaurant_backups/); assert.match(migration,/realtime_events/); assert.match(migration,/print_jobs/);
assert.match(bridge,/PRINTER_HOST/); assert.match(bridge,/print-jobs/);
assert.match(server,/\/api\/admin\/orders/); assert.match(server,/\/api\/admin\/order-events/);
assert.match(migration,/order_items_order_restaurant_fk/); assert.match(migration,/storage\.buckets/);
console.log('TokioInbox V25 smoke: OK');
